package io.akka.umami.lib;

import java.util.List;
import java.util.regex.Pattern;

/**
 * Whether a user agent announces itself as a robot.
 *
 * <p>The original asks the `isbot` package, which holds 209 regular expressions and tests a
 * user agent against all of them at once, case-insensitively. The answer decides whether an event
 * is recorded at all — a robot's request is accepted with 200 and stored nowhere — so a list that
 * merely resembles it disagrees about real traffic. This is that list, translated pattern for
 * pattern by `umami-port/probes/generate_bots.py`, not an approximation of it.
 *
 * <p>The patterns are the `isbot` project's work, MIT-licensed, and are recorded in
 * ACKNOWLEDGEMENTS.md as copied.
 */
public final class Bots {

  private Bots() {}

  /** Every pattern, kept separate so one that fails to compile is visible rather than silent. */
  public static final List<String> PATTERNS =
      List.of(
          " daum[ /]",
          " deusu/",
          "(?:^|[^g])news(?!sapphire)",
          "(?<! channel/|google/)google(?!(?:wv|app|/google| pixel))",
          "(?<! cu)bots?(?:\\b|_)",
          "(?<!cam)scan",
          "(?<!lib)http",
          "24x7",
          ";\\s\\w+;$",
          "@[a-z][\\w-]+\\.",
          "\\(\\)",
          "\\.com\\b",
          "\\b\\w+\\.ai",
          "\\bbw/",
          "\\bdlc\\b",
          "\\bort/",
          "\\bperl\\b",
          "\\btime/",
          "\\|",
          "^[<\\(;]",
          "^[\\w \\.\\-\\(?:\\):%]+(?:/v?\\d+(?:\\.\\d+)?(?:\\.\\d{1,10})*?)?(?:,|$)",
          "^[\\w\\-]+/[\\w]+$",
          "^[^ ]{50,}$",
          "^\\d+\\b",
          "^\\w*search\\b",
          "^\\w+/[\\w\\(\\)]*$",
          "^\\w+/\\d\\.\\d\\s\\([\\w@]+\\)$",
          "^active",
          "^ad muncher",
          "^amaya",
          "^apache/",
          "^avsdevicesdk/",
          "^azure",
          "^biglotron",
          "^blackbox exporter",
          "^bot",
          "^clamav[ /]",
          "^claude-code/",
          "^client/",
          "^cobweb/",
          "^custom",
          "^ddg[_-]android",
          "^discourse",
          "^dispatch/\\d",
          "^downcast/",
          "^duckduckgo",
          "^email",
          "^exodusmovement",
          "^facebook",
          "^getright/",
          "^gozilla/",
          "^hobbit",
          "^hotzonu",
          "^hwcdn/",
          "^igetter/",
          "^jeode/",
          "^jetty/",
          "^jigsaw",
          "^microsoft bits",
          "^movabletype",
          "^mozilla/\\d\\.\\d\\s[\\w\\.-]+$",
          "^mozilla/\\d\\.\\d\\s\\((?:compatible;)?(?:\\s?[\\w\\d-.]+\\/\\d+\\.\\d+)?\\)$",
          "^navermailapp",
          "^netsurf",
          "^offline",
          "^openai/",
          "^owler",
          "^php",
          "^postman",
          "^ps_daily/",
          "^python",
          "^rank",
          "^read",
          "^reed",
          "^remove\\.bg/",
          "^rest",
          "^rss",
          "^snapchat",
          "^sora ",
          "^space bison",
          "^stape/",
          "^svn",
          "^swcd ",
          "^taringa",
          "^thumbor/",
          "^track",
          "^w3c",
          "^webbandit/",
          "^webcopier",
          "^wget",
          "^whatsapp",
          "^wordpress",
          "^xenu link sleuth",
          "^yahoo",
          "^yandex",
          "^zdm/\\d",
          "^zoom marketplace/",
          "abuse",
          "advisor",
          "agent\\b",
          "analyzer",
          "archive",
          "ask jeeves/teoma",
          "attracta",
          "audit",
          "bluecoat drtr",
          "browsex",
          "burpcollaborator",
          "capture",
          "catch",
          "check\\b",
          "checker",
          "chrome-lighthouse",
          "chromeframe",
          "classifier",
          "cloudflare",
          "collapsify\\b",
          "convertify",
          "cookiehubverify/",
          "crawl",
          "cursor/",
          "cypress/",
          "dareboost",
          "datanyze",
          "dejaclick",
          "detect",
          "discovery",
          "dmbrowser",
          "download",
          "exaleadcloudview",
          "feed",
          "fetcher",
          "firephp",
          "foregenix",
          "functionize",
          "grab",
          "hardenize\\b",
          "headless",
          "hotjar",
          "httrack",
          "hubspot marketing grader",
          "ibisbrowser",
          "infrawatch",
          "insight",
          "inspect",
          "iplabel",
          "java(?!;)",
          "library",
          "linkcheck",
          "linktiger",
          "mail\\.ru/",
          "manager",
          "manus-user/",
          "marketgoo/",
          "measure",
          "monitor\\b",
          "neustar wpm",
          "node\\b",
          "nutch",
          "offbyone",
          "openvas",
          "optimize",
          "pageburst",
          "pagespeed",
          "parser",
          "phantomjs",
          "pingdom",
          "playwright",
          "powermarks",
          "preview",
          "productfinder",
          "prospectingstudio",
          "proxy",
          "ptst[ /]\\d",
          "radar",
          "readable/",
          "retriever",
          "rexx;",
          "rigor",
          "rss\\b",
          "scrape",
          "securityheaders",
          "selenium",
          "server",
          "silktide",
          "sindup/",
          "sogou",
          "sparkler/",
          "speedcurve",
          "spider",
          "splash",
          "statuscake",
          "supercleaner",
          "synapse",
          "synthetic",
          "testlocally",
          "tools",
          "torrent",
          "transcoder",
          "upday/",
          "url",
          "validator",
          "virtuoso",
          "wappalyzer",
          "watchtowr",
          "webglance",
          "webkit2png",
          "whatcms/",
          "xtate/");

  private static final Pattern ANY =
      Pattern.compile(String.join("|", PATTERNS), Pattern.CASE_INSENSITIVE);

  /**
   * A user agent that is absent is a robot, which is what the original's own check amounts to:
   * `isbot(undefined)` is false, but the collection route refuses a payload with no user agent
   * before it gets there.
   */
  public static boolean isBot(String userAgent) {
    if (userAgent == null || userAgent.isBlank()) {
      return true;
    }
    return ANY.matcher(userAgent).find();
  }
}
